TravelAgency/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Model;

namespace TravelAgency.Controllers
{
    public class CityController : Controller
    {
        // GET: City
        public ActionResult Show(int id)
        {
            City city = DataAccess.Cities.GetCity(id);
            city.Hotels = DataAccess.Hotels.GetCityHotels(id);
            city.TouristicSites= DataAccess.TouristicSites.GetCityTouristicSites(id);
            city.Restaurants= DataAccess.Restaurants.GetCityRestaurants(id);
            city.TravelAgencyBranches = DataAccess.TravelAgencyBranches.GetCityBranches(id);
            foreach (var tabranch in city.TravelAgencyBranches)
            {
                tabranch.AgencyName = DataAccess.TravelAgencies.GetById(tabranch.TravelAgencyId).Name;
            }
            return View(city);
        }
    }
}

TravelAgency/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelAgency.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.TravelAgencies = DataAccess.TravelAgencies.GetAll();
            return View(TravelAgency.DataAccess.Provinces.GetAll());
        }
    }
}

TravelAgency/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Model;

namespace TravelAgency.Controllers
{
    public class HotelController : Controller
    {
        // GET: Hotel
        public ActionResult Show(int id)
        {
            Hotel h = DataAccess.Hotels.GetById(id);
            var city = DataAccess.Cities.GetCity(h.CityId);
            h.CityName = city.Name;
            h.ProvinceName = DataAccess.Provinces.GetById(city.ProvinceId).Name;
            return View(h);
        }
    }
}

TravelAgency/Controllers/ProvinceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Model;

namespace TravelAgency.Controllers
{
    public class ProvinceController : Controller
    {
        // GET: Province
        public ActionResult Show(int id)
        {
            Province province = DataAccess.Provinces.GetById(id);
            province.CalculatedPopulation = DataAccess.Provinces.GetTotalPopulation(id);
            province.Cities = DataAccess.Cities.GetProvinceCities(id);
            return View(province);
        }
    }
}

TravelAgency/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Model;

namespace TravelAgency.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Show(int id )
        {
            Restaurant r = DataAccess.Restaurants.GetById(id);
            return View(r);
        }
    }
}

TravelAgency/Controllers/TouristicSiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelAgency.Controllers
{
    public class TouristicSiteController : Controller
    {
        // GET: TouristicSite
        public ActionResult Show(int id )
        {
            var s = DataAccess.TouristicSites.GetById(id);
            return View(s);
        }
    }
}

TravelAgency/Controllers/TravelAgencyBranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelAgency.Controllers
{
    public class TravelAgencyBranchController : Controller
    {
        public ActionResult Show(int id)
        {
            Model.TravelAgencyBranch r = DataAccess.TravelAgencyBranches.GetById(id);
            r.AgencyName = DataAccess.TravelAgencies.GetById(r.TravelAgencyId).Name;
            return View(r);
        }
    }
}

TravelAgency/Controllers/TravelAgencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Model;

namespace TravelAgency.Controllers
{
    public class TravelAgencyController : Controller
    {
        // GET: TravelAgency

        public ActionResult Show(int id)
        {
            Model.TravelAgency r = DataAccess.TravelAgencies.GetById(id);
            r.Branches = DataAccess.TravelAgencyBranches.GetAgencyBranches(id);
            foreach (var b in r.Branches)
                b.CityName = DataAccess.Cities.GetCity(b.CityId).Name;
            return View(r);
        }
    }
}

TravelAgency/Views/City/Show.cshtml
@model TravelAgency.Model.City
@{
    ViewBag.Title = string.Format("{0}", Model.Name);
}
@if (Model == null)
{
    <p>City not found</p>
}
else
{
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-users fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@Model.Population</div>
                            <div>Population</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-cutlery  fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@Model.Restaurants.Count</div>
                            <div>Restaurant</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-bed fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@Model.Hotels.Count</div>
                            <div>Hotels</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-plane fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@Model.TouristicSites.Count</div>
                            <div>Touristic Sites</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Hotels
                </div>
                <div class="panel-body">

                    <div class="list-group">
                        @foreach (var item in Model.Hotels)
                        {
                            <a href="@Url.Action("Show","Hotel",new {id=item.Id })" class="list-group-item">
                                <i class="fa fa-info fa-fw"></i> @item.Name
                                <span class="pull-right text-muted small">
                                    <em>@item.ServiceQuality Stars</em>
                                </span>
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Restaurants
                </div>
                <div class="panel-body">
                    @foreach (var item in Model.Restaurants)
                    {
                        <a href="@Url.Action("Show","Restaurant",new {id=item.Id })" class="list-group-item">
                            <i class="fa fa-info fa-fw"></i> @item.Name
                            @*<span class="pull-right text-muted small">
                                <em>@item.Specialties</em>
                            </span>*@
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Touristic Sites
                </div>
                <div class="panel-body">
                    @foreach (var item in Model.TouristicSites)
                    {
                        <a href="@Url.Action("Show","TouristicSite",new {id=item.Id })" class="list-group-item">
                            <i class="fa fa-info fa-fw"></i> @item.Type
                            <span class="pull-right text-muted small">
                                @*<em>@item.Specialties</em>*@
                            </span>
                        </a>
                    }
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Travel Agency Branches
                </div>
                <div class="panel-body">
                    @foreach (var item in Model.TravelAgencyBranches)
                    {
                        <a href="@Url.Action("Show","TravelAgencyBranch",new {id=item.Id })" class="list-group-item">
                            <i class="fa fa-info fa-fw"></i> @item.Name
                            <span class="pull-right text-muted small">
                                <em>@item.AgencyName</em>
                            </span>
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Map
                </div>
                <div class="panel-body">

                    <div style="height:200px;">
                        <div id="map">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section scripts{
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrzu7GuhAnOodLklDe5JT9lmtVoeo30yA&callback=initMap" async defer></script>
        <script>
            var map;
            function initMap() {
                map = new google.maps.Map(document.getElementById('map'), {

                    center: { lat: @Globals.CleanString( Model.Latitude), lng: @Globals.CleanString( Model.Longtude) },
                    zoom: 10
                });
            }
        </script>

    }
}

TravelAgency/Views/Home/Index.cshtml
@model List<TravelAgency.Model.Province>
@{
    ViewBag.Title = "Home Page";
}
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Registered Provinces
            </div>
            <div class="panel-body">
                <div class="list-group">
                    @foreach (var prov in Model)
                    {
                        <a href="@Url.Action("Show","Province",new {id=prov.Id })" class="list-group-item">@prov.Name</a>
                    }
                </div>
            </div>
            <div class="panel-footer">
                Total Provinces : @Model.Count
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Registered Travel Agencies
            </div>
            <div class="panel-body">
                <div class="list-group">
                    @foreach (var ag in ViewBag.TravelAgencies)
                    {
                        <a href="@Url.Action("Show","TravelAgency",new {id=ag.Id })" class="list-group-item">@ag.Name</a>
                    }
                </div>
            </div>
            <div class="panel-footer">
                Total Travel Agencies  : @ViewBag.TravelAgencies.Count
            </div>
        </div>
    </div>

</div>

TravelAgency/Views/Hotel/Show.cshtml
@model TravelAgency.Model.Hotel

@{
    ViewBag.Title = Model.Name;
    ViewBag.Subtitle = Model.ServiceQuality + " Stars";
}

<div class="row">
    <div class="col-md-6">
        <p>Information</p>
        <div class="list-group">

            <a href="#" class="list-group-item">
                <i class="fa  fa-phone-square   fa-fw"></i> Phone Number
                <span class="pull-right text-muted small">
                    <em>@Model.Tel</em>
                </span>
            </a>
            <a href="#" class="list-group-item">
                <i class="fa fa-comment fa-fw"></i> City
                <span class="pull-right text-muted small">
                    <em>@Model.CityName</em>
                </span>
            </a>
            <a href="#" class="list-group-item">
                <i class="fa fa-comment fa-fw"></i> Province
                <span class="pull-right text-muted small">
                    <em>@Model.ProvinceName</em>
                </span>
            </a>
            <a href="#" class="list-group-item">
                <i class="fa fa-star   fa-fw"></i>Service Quality
                <span class="pull-right text-muted small">
                    <em>@Model.ServiceQuality</em>
                </span>
            </a>
        </div>

    </div>
    <div class="col-md-6">
        <div style="height:200px;">
            <div id="map">

            </div>
        </div>
        @section scripts{
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrzu7GuhAnOodLklDe5JT9lmtVoeo30yA&callback=initMap" async defer></script>
            <script>
            var map;
            function initMap() {
                map = new google.maps.Map(document.getElementById('map'), {
                    
                center: { lat: @Globals.CleanString( Model.Latitude), lng: @Globals.CleanString( Model.Longitude) },
                    zoom: 8
                });
            }
                @*var geocoder;
                var map;

                function initialize() {

                    geocoder = new google.maps.Geocoder();

                    var latlng = new google.maps.LatLng(@Globals.CleanString( Model.Latitude), @Globals.CleanString(Model.Longitude ));
                    var mapOptions = {
                        zoom: 8,
                        center: latlng
                    };

                    map = new google.maps.Map(document.getElementById("map"), mapOptions);

                    // Call the codeAddress function (once) when the map is idle (ready)
                    google.maps.event.addListenerOnce(map, 'idle', codeAddress);
                }

                function codeAddress() {

                    // Define address to center map to
                    var address = '@Model.Latitude, @Model.Longitude';

                    geocoder.geocode({
                        'address': address
                    }, function (results, status) {

                        if (status == google.maps.GeocoderStatus.OK) {

                            // Center map on location
                            map.setCenter(results[0].geometry.location);

                            // Add marker on location
                            var marker = new google.maps.Marker({
                                map: map,
                                position: results[0].geometry.location
                            });

                        } else {

                            alert("Geocode was not successful for the following reason: " + status);
                        }
                    });
                }

                initialize();*@
            </script>
        }

    </div>
</div>

TravelAgency/Views/Province/Show.cshtml
@model TravelAgency.Model.Province
@{
    ViewBag.Title = string.Format("Province : {0}", Model.Name);
}

@if (Model == null)
{
    <p>Not Found</p>
}
else
{
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-users fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@Model.CalculatedPopulation</div>
                            <div>Population</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="glyphicon glyphicon-flag fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@Model.Cities.Count</div>
                            <div>Cities</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="glyphicon glyphicon-phone-alt fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">@Model.TelCode</div>
                            <div>Phone Code</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="glyphicon glyphicon-map-marker fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="large" style="margin-bottom:35px;">@Model.Region</div>
                            <div>Region</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> Cities Population
                </div>
                <div class="panel-body">
                    <div id="morris-donut-chart"></div>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <div class="col-lg-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> List of Cities 
                </div>
                <div class="panel-body">
                    <table class="table table-no-border m-0">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Population</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            @foreach (var city in Model.Cities)
                            {
                                <tr>
                                    <td>@city.Name</td>
                                    <td>@city.Population</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
    </div>
    @section scripts{
        <script>
            Morris.Donut({
                element: 'morris-donut-chart',
                data: [
                    @foreach(var city in Model.Cities)
                    {
                       @( Html.Raw(string.Format("{{ label: \'{0}\', value: {1}, click: '{2}'}},", city.Name, city.Population,Url.Action("Show","City",new { id=city.Id }))));
                    }
                ],
                resize: true
            }).on('click', function (i, row) {
                console.log(i, row);
                document.location = $(row).attr("click");
            });;
        </script>
    }
}

TravelAgency/Views/Restaurant/Show.cshtml
@model TravelAgency.Model.Restaurant

@{
    ViewBag.Title = Model.Name;
        
}
<div class="row">
    <div class="col-mg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Restaurant Adress
            </div>
            <div class="panel-body">
                <h4>
                    @Model.Address
                </h4>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-mg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Specialties
            </div>
            <div class="panel-body">
                <ul>
                    @foreach (var sp in Model.Specialties.Split('\\'))
                    {
                        <li>@sp</li>
                    }
                </ul>
            </div>
        </div>
    </div>

</div>

TravelAgency/Views/Shared/_CitiesSideBar.cshtml
@foreach (var province in Globals.AllProvinces)
{
    <li>
        <a href="@Url.Action("Show","Province",new { id=province.Id})"><i class="fa fa-star fa-fw"></i> @province.Name <span class="fa arrow"></span></a>
        @if(province.Cities!=null && province.Cities.Count > 0)
        {
            <ul class="nav nav-second-level">
                @foreach (var city in province.Cities)
                {
                    <li>
                        <a   href="@Url.Action("Show","City",new { id=city.Id})"> <i class="fa  fa-play"></i> &nbsp; @city.Name</a>
                    </li>
                }
            </ul>
        }
    </li>
}

TravelAgency/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TravelAgency/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Tourism Service DB</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    @*<link href="../dist/css/sb-admin-2.css" rel="stylesheet">*@
    <link href="~/Content/sb-admin-2.css" rel="stylesheet" />
    <!-- Morris Charts CSS -->
    <link href="~/vendor/morrisjs/morris.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <!-- Custom Fonts -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Tourism Service Providers Database</a>
            </div>
            <!-- /.navbar-header -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        @Html.Partial("_CitiesSideBar")
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">@ViewBag.Title <small>@(ViewBag.Subtitle)</small></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            @RenderBody()
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/vendor/raphael/raphael.min.js"></script>
    <script src="~/vendor/morrisjs/morris.min.js"></script>
    <!-- Custom Theme JavaScript -->
    @*<script src="../dist/js/sb-admin-2.js"></script>*@
    <script src="~/Scripts/sb-admin-2.js"></script>
    @RenderSection("scripts", false)

</body>
</html>

TravelAgency/Views/TouristicSite/Show.cshtml
@model TravelAgency.Model.TouristicSite
@{
    ViewBag.Title = Model.Name;
}

TravelAgency/Views/TravelAgency/Show.cshtml
@model TravelAgency.Model.TravelAgency
@{
    ViewBag.Title = Model.Name;
}

<div class="row">
    <div class="col-md-7">
        <div class="panel panel-default">
            <div class="panel-heading">Headquarters Address</div>
            <div class="panel-body">
                <h3> @Model.HeadquartersAddress</h3>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="panel panel-default">
            <div class="panel-heading">Phone Numbr</div>
            <div class="panel-body">
                <h3>@Model.TelNo</h3>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Branches</div>
            <div class="panel-body">
                <div class="list-group">
                    @foreach (var item in Model.Branches)
                    {
                        <a href="@Url.Action("Show","TravelAgencyBranch",new {id=item.Id })" class="list-group-item">
                            <i class="fa fa-info fa-fw"></i> @item.Name
                            <span class="pull-right text-muted small">
                                <em>@item.CityName</em>
                            </span>
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TravelAgency/Views/TravelAgencyBranch/Show.cshtml
@model TravelAgency.Model.TravelAgencyBranch
@{
    ViewBag.Subtitle = Model.AgencyName;
    ViewBag.Title= Model.Name;
}


<div class="row">
    <div class="col-md-7">
        <div class="panel panel-default">
            <div class="panel-heading">Address</div>
            <div class="panel-body">
                <h3>@Model.Address</h3>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="panel panel-default">
            <div class="panel-heading">Phone</div>
            <div class="panel-body">
                <h3>@Model.TelNo</h3>
            </div>
        </div>
    </div>
</div>